### ISSUE TITLE
Incorrect rendering with html`<textarea>${undefined}</textarea>`

### ISSUE THREAD

**Issue by coreyfarrell** [WebReflection/uhandlers#2]
```js
import {render, html} from 'uhtml';

render(document.body, html`<textarea>${undefined}</textarea>`);
console.log(document.body.innerHTML);
```

This creates a textarea element with `<!--isµ0-->` displayed as the current value - the console.log displays `<textarea>&lt;!--isµ0--&gt;</textarea>`.  Note the `<!--isµ0-->` also ends up inside the `<style>` element but this is less harmful as the style element just ignores the invalid content.

I think this could be fixed if the `text` function initialized `let oldValue = node.textContent;` - this way it would start with `<!--isµ0-->` instead of undefined so it wouldn't match `newValue` on the first call.

**Comment by WebReflection** [comment]
this is covered here:
https://github.com/WebReflection/uhtml/blob/master/esm/rabbit.js#L96-L102

not sure why you'd open a bug in here? 🤔

**Comment by WebReflection** [comment]
although I see `oldValue = node.textContent` *might* fix the issue, but I'm not sure it should be responsibility of the handler to do that ... I think this bug belongs to uhtml

**Comment by WebReflection** [comment]
This has been fixed in *uhtml*, landed as patch 👋

**Comment by coreyfarrell** [comment]
To put this in terms of `uhandlers` only:
```js
import {text} from 'uhandlers';

document.body.innerHTML = '<textarea>content</textarea>';
const resetValue = text(document.body.firstChild);
resetValue(undefined);

console.log(document.body.innerHTML); // should this be `<textarea></textarea>`?
```

Maybe I'm misunderstanding what this example code should do.  In any case thanks for the uhtml fix!

**Comment by WebReflection** [comment]
This code should do nothing if the new value is the same as the old one ... and that's what it does. The fact you pass `undefined` it's not this code matter, as this works as expected to me (and you should not pass undefined around ;-) )

uhtml is the one responsible for finding *holes* and in this case, as the *hole* is undesired as content, it should be the one cleaning up its own workarounds for style and textarea nodes.
